### ISSUE TITLE
Can't use invalid edn as input to a cli

### ISSUE THREAD

**Issue by dpetran** [ruedigergad/cli4clj#4]
We have cli program that has valid inputs that aren't valid edn. For example, we allow users to specify ids that have a slash in them: `12345/abc`. cli4clj runs this through the clojure `read` function, which crashes when trying to read this - it thinks it's an invalid number.

Would it be possible to allow the `read` function to be pluggable, similar to how `eval` is pluggable? Or is there some other way to work around this issue?

**Comment by ruedigergad** [comment]
Hi,

thanks a lot for the feedback.
I already started to look into this.
Unfortunately, I am very busy these days and will need a bit more time.

Cheers,

Ruediger

**Comment by dpetran** [comment]
I understand that this is a big change - we've got a workaround that will suffice for the short term. I am curious to hear your thoughts once you've had a chance to consider : )

**Comment by ruedigergad** [comment]
I uploaded version 1.7.10 with the following changes:

- When an invalid number is encountered, e.g., 123/abc, now, by default a string is returned. This behaviour can be disabled by setting `:invalid-token-to-string false` in the CLI opts, which will cause the error to surface instead of doing the string conversion fallback.
- The read function can be customized by setting `:read-fn` in the CLI opts to a custom read function. The read function has to accept two arguments, opts and stream. See https://github.com/ruedigergad/cli4clj/blob/20b58fb86890028ef01a2c86ebfa1291b1dcbea2/test/cli4clj/test/cli.clj#L337 for an example.

If you need more information let me know.

I hope this addresses what you had in mind.



Cheers,
Ruediger

**Comment by dpetran** [comment]
Thanks for the quick turnaround! This fixes the problem for us.. :+1:
